from __future__ import annotations

from osr_map_maker import (
    CURRENT_SCHEMA_VERSION,
    DEFAULT_EXPORT_PROFILES,
    DEFAULT_FILENAME_TEMPLATE,
    DEFAULT_SHORTCUTS,
    EXPORT_FRAME_PRESETS,
    LAYER_DEFS,
    MAP_MODES,
    MAP_TEMPLATE_NAMES,
    SYMBOL_GROUPS,
    SYMBOL_LABELS,
    TEXTURE_FILL_TYPES,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "DEFAULT_EXPORT_PROFILES",
    "DEFAULT_FILENAME_TEMPLATE",
    "DEFAULT_SHORTCUTS",
    "EXPORT_FRAME_PRESETS",
    "LAYER_DEFS",
    "MAP_MODES",
    "MAP_TEMPLATE_NAMES",
    "SYMBOL_GROUPS",
    "SYMBOL_LABELS",
    "TEXTURE_FILL_TYPES",
]
