from __future__ import annotations

from validation import validate_project_document
from geometry import point_in_polygon, points_bounds, quadratic_curve_points, rects_overlap, rotate_xy

from osr_map_maker import (
    CURRENT_SCHEMA_VERSION,
    bounds,
    campaign_room_fields,
    create_project,
    default_layers,
    diagonal_corridor,
    export_project_for_frame,
    fog_of_war_masks,
    fantasy_grounds_xml,
    foundry_scene_data,
    generated_dungeon_objects,
    hex_coordinate_label,
    hex_cell_center,
    import_roll_table_text,
    line_of_sight_clear,
    light_zones,
    map_mode_feature_summary,
    print_layout_plan,
    legend_obj,
    note_obj,
    encounter_start_points,
    rect,
    roll20_page_data,
    underlay_alignment_transform,
    room_number_token,
    shape,
    symbol,
    text_obj,
    validate_object,
    validate_project,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "bounds",
    "campaign_room_fields",
    "create_project",
    "default_layers",
    "diagonal_corridor",
    "export_project_for_frame",
    "fog_of_war_masks",
    "fantasy_grounds_xml",
    "foundry_scene_data",
    "generated_dungeon_objects",
    "hex_coordinate_label",
    "hex_cell_center",
    "import_roll_table_text",
    "line_of_sight_clear",
    "light_zones",
    "map_mode_feature_summary",
    "print_layout_plan",
    "legend_obj",
    "note_obj",
    "encounter_start_points",
    "rect",
    "roll20_page_data",
    "underlay_alignment_transform",
    "room_number_token",
    "shape",
    "symbol",
    "text_obj",
    "validate_object",
    "validate_project_document",
    "point_in_polygon",
    "points_bounds",
    "quadratic_curve_points",
    "rects_overlap",
    "rotate_xy",
    "validate_project",
]
